### ISSUE TITLE
[BMT] Add scrollbar

### ISSUE THREAD

**Issue by rebekkategtmeier** [andriisemenov/equihub-brain-issue-tracking#26]
Me as a host and founder, 
would like to see all inputs after eachother and not have all information flying into another. See the picture below for comment.

**Comment by rebekkategtmeier** [comment]
![image](https://user-images.githubusercontent.com/76179547/121770336-09b82600-cb69-11eb-9168-a957bf8ae6bf.png)

**Comment by andriisemenov** [comment]
Add scrollbar to the BMT fields.

**Comment by kochjh** [comment]
I added a scrollbar and I also adjusted the padding between text and switch, because in some cases the text could overlap it (depending on where line break is)
![image](https://user-images.githubusercontent.com/49067305/121816255-dd8cca00-cc7a-11eb-8004-433ed8000ddd.png)

**Comment by rebekkategtmeier** [comment]
Hey, is it pushed already? I tried to test it but even with deleting the cash I have the old view.

**Comment by kochjh** [comment]
Hey, it is pushed but not merged and deployed yet.
Next time I will close the ticket after the merge for better transparency.
