### ISSUE TITLE
[Frontend] Input fields 

### ISSUE THREAD

**Issue by rebekkategtmeier** [andriisemenov/equihub-brain-issue-tracking#41]
Hi everyone, 
as a tooluser I would like to have separated and long input fields for content entries so that I can easily see and understand the text and know what was written this also includes the showing of the whole sentence. 

Today I was giving in the first Sub-Steps for our master sprint planning and recognized that the input fields are not seperated enough in the story dialog, see picture below. 

![image](https://user-images.githubusercontent.com/76179547/110914966-6102ec00-8317-11eb-8829-8be3676f3cf5.png)

Outcomes and Acceptance Criteria: 
- [x] The lenght of the input fields is attached to the input the user gives and is dynamically changing
- [x] The user can easily read the input because it is separated by a blank space
- [x] change the wording of the fields so that the whole sentence is visible 
- [x] The input fields are dynamically changing in all dialogs of the tool

**Comment by rebekkategtmeier** [comment]
the same issue occured in the BMT view 
![image](https://user-images.githubusercontent.com/76179547/117408077-b4f11200-af0f-11eb-80b3-6812fae6efea.png)

**Comment by rebekkategtmeier** [comment]
![image](https://user-images.githubusercontent.com/76179547/118816831-e1fbd800-b8b2-11eb-8d8a-45ce4fc6082e.png)

**Comment by rebekkategtmeier** [comment]
all dialogs should be shown easily so that I can read without clicking into it or scrolling.

**Comment by andriisemenov** [comment]
1h for all input fields on the platform. + 30 mins design discussion.

**Comment by rebekkategtmeier** [comment]
Also Check the follwing tickets while working on the template: https://github.com/andriisemenov/equihub-brain-issue-tracking/issues/85

**Comment by andriisemenov** [comment]
- [ ] Outline the fields
- [ ] Implement margin 12px

**Comment by kochjh** [comment]
This would be outlined input fields with a little bit higher margin:

![image](https://user-images.githubusercontent.com/49067305/126876587-f57445e6-37dc-4ce0-aff2-697cd688d85f.png)

With text in the fields:

![image](https://user-images.githubusercontent.com/49067305/126876652-775746f6-8751-4df8-ba5a-3ea104a14d22.png)

Is this fine for you?

**Comment by kochjh** [comment]
Fields filled, increase margin between submit button and last field
