### ISSUE TITLE
I can see the Flows of another Host without them actively having shared them to me, my organization or similar

### ISSUE THREAD

**Issue by jonaself** [andriisemenov/equihub-brain-issue-tracking#45]
When I login as Host, and want to "move a Team to a Flow" by clicking the 3 black dots icon for "move" to then "choose" which flow, I can see a suggested list of Flows (which I first understood as data of "Project Names" or something), which **includes data from a domain (edit: the domain of "anothers Hosts (Organization) Templates") I should not be able to access I think.** 

I dont know what the last status of preliminary decision-making on this topic was, so dont take it as an acute request, but following your wish to it being listed here as a bug, my point was more raising awareness and implicating that there might need to come a deep dive workshop for Privacy and Security issues, and I tried communicating this with a media input that supports the message. I've also refined that message to better outline the big target conflict of both strategies.

It is a critical request though (Kano: Hygienical/required by Stakeholder: Law), as its about sensitive, valuable information (for if this goes into some capacity prioritization plan according to Eisenhower haha)

**Comment by rebekkategtmeier** [comment]
![image](https://user-images.githubusercontent.com/76179547/114068268-07ea9180-989e-11eb-8cc1-3e06158c4493.png)
