### ISSUE TITLE
[resource exchange] delete demand

### ISSUE THREAD

**Issue by rebekkategtmeier** [andriisemenov/equihub-brain-issue-tracking#48]
Me as a resource giver, 
would like to delete a resource which I do not need anymore or have not needed resources automatic deleted. 

I have tried to delete the resources which were named in the resource exchange part of the tool to clear it out for a showcase. If I click on the delete button the resource response dialog is opening but I cannot delete the feature. Furthermore it would be great if demand would be automatically deleted if an response was accepted or if they are not relevant anymore. 
If we would add the demand request to a story we could delete it automatically when a story was closed or the sprint ended and the story was not shifted to a new sprint.

![image](https://user-images.githubusercontent.com/76179547/114896204-6cfb3580-9e10-11eb-8cbb-84dab1d4e42f.png)

**Comment by andriisemenov** [comment]
First, the backend function needs to be implemented.
Frontend estimation: 15m - 1h.

**Comment by andriisemenov** [comment]
Backend function is ready, example:
mutation{
  deleteDemand(id:"024e1d02-5e17-48b2-8157-b490b0952c38")
}

**Comment by kochjh** [comment]
I resolved the bug, so you can now manually delete the resource demand using the dialog.
Is automation already taking place on this issue? The possibility to accept a response is still missing or not?

**Comment by andriisemenov** [comment]
New ticket for demand/resource design/logic #91
