### ISSUE TITLE
[BMT] switching between flow view and BMT

### ISSUE THREAD

**Issue by rebekkategtmeier** [andriisemenov/equihub-brain-issue-tracking#58]
I really had the problem at first to find the BMT view.
I was wondering if it would be more easy to use two button instead of the drop down. 
like this : 
![image](https://user-images.githubusercontent.com/76179547/117461555-fef8e880-af4d-11eb-9a64-c776cf042b38.png)
![image](https://user-images.githubusercontent.com/76179547/117461792-40899380-af4e-11eb-83fe-6079750fd82a.png)

**Comment by andriisemenov** [comment]
Estimation: 30m-1.5h

**Comment by rebekkategtmeier** [comment]
on the team side the BMT is always the first thing to see basically the homebase. 
This means you dont have flow view and BMT view you just have the home button which leads to the BMT and will be on the navigation at the side.

**Comment by kochjh** [comment]
But users still need a possibility to navigate to their sprints or is this not required? Like this:
![image](https://user-images.githubusercontent.com/49067305/123106711-28f06680-d439-11eb-94f1-73c71217fe0d.png)

The tooltip of the flow icon (now home icon) was "Team flow". Should I change it to "Home" or something similar?

**Comment by rebekkategtmeier** [comment]
The question is on which user side you are in the tool. 
On the side of the Host, you will have the teams buttom, the flow button and the resource button. 
On the side of the team you have the home button, the flow (sprint) button and the resource button 
If you have further questions just call :)
