### ISSUE TITLE
Privacy Document not all times viewable/accessible

### ISSUE THREAD

**Issue by jonaself** [andriisemenov/equihub-brain-issue-tracking#64]
Users always need to be able to see the privacy document, it has to be accessible from all Screens, but its not viewable while using/testing the product currently.

![image](https://user-images.githubusercontent.com/70448018/118510190-0334bb00-b731-11eb-9242-bf7176915ed3.png)

**Comment by rebekkategtmeier** [comment]
integration with a click on the policy icon
