### ISSUE TITLE
Impressum not visible

### ISSUE THREAD

**Issue by jonaself** [andriisemenov/equihub-brain-issue-tracking#65]
The impressum is not visible, but has to be due to german law. We have to include our impressum, currently this is shown when you guess about clicking on equihub next to the Copyright info to find about whos providing this service:
![image](https://user-images.githubusercontent.com/70448018/118511492-3e83b980-b732-11eb-82a0-18ffe10d8bfa.png)

**Comment by rebekkategtmeier** [comment]
impressum and terms and conditions were integrated :)

**Comment by rebekkategtmeier** [comment]
Great job :*
