### ISSUE TITLE
[BMT] Integrate Why and How 

### ISSUE THREAD

**Issue by rebekkategtmeier** [andriisemenov/equihub-brain-issue-tracking#67]
Me as a host, 
I would like to see the why and how of the team in the business model twin, because I think it is very valuable for the team to see all the time and remember it. Furthermore it can be used for the communication to third parties as an easy and awareness generating introduction which helps me as a coach to introduce the team. 

The following two options were discussed with Kostja today in a call. 
![image](https://user-images.githubusercontent.com/76179547/119671920-74aff000-be3a-11eb-92a7-fd77b60f5be5.png)

![image](https://user-images.githubusercontent.com/76179547/119673130-6adabc80-be3b-11eb-9618-b21a8a106f86.png)

**Comment by andriisemenov** [comment]
@kochjh let's align when you are ready to work on this issue.

**Comment by andriisemenov** [comment]
The bars should be above one another. Ideally it will be a session with Jan where changes are made live.

**Comment by rebekkategtmeier** [comment]
![image](https://user-images.githubusercontent.com/76179547/124801296-fa08e300-df56-11eb-993d-622528d3e7c8.png)
