### ISSUE TITLE
[BMT] design how to mark Hypothesis true / wrong  

### ISSUE THREAD

**Issue by rebekkategtmeier** [andriisemenov/equihub-brain-issue-tracking#68]
Me as a host, 
would like to see how the hypothesis was validated and which were the main and key results of the validation so that I can see if the right obligation was made so that I can give feedback or open up the view of the team because I can see other possibilities. Therefore I would like to see the title, the description and the metric as well as an input field for the key results and the extrapolation. 
 
![image](https://user-images.githubusercontent.com/76179547/119691295-be083b80-be4a-11eb-99b0-021b5802b14f.png)

**Comment by andriisemenov** [comment]
Discussing the final design in this sprint

**Comment by rebekkategtmeier** [comment]
https://miro.com/app/board/o9J_lCOTMZ4=/

**Comment by andriisemenov** [comment]
Cunclusion:

Add findings field with +

Remove general "comment" field

Add a possibility to add several findings

Show who added the finding

**Comment by andriisemenov** [comment]
Learning vs Finding vs Insight

**Comment by rebekkategtmeier** [comment]
Its decided it will be finding 👍

**Comment by rebekkategtmeier** [comment]
![image](https://user-images.githubusercontent.com/76179547/123217938-6998c000-d4cb-11eb-85e8-1c20a508bd27.png)
![image](https://user-images.githubusercontent.com/76179547/123217975-75848200-d4cb-11eb-9bd9-669c0b5cd96b.png)

**Comment by rebekkategtmeier** [comment]
Opened a new Ticket for Development #89
