### ISSUE TITLE
Creative Commons license implementation below BMC

### ISSUE THREAD

**Issue by jonaself** [andriisemenov/equihub-brain-issue-tracking#73]
We have to include a reference according to the license of the Business Model Canvas, which is a share-alike Creative Commons license.
- show creative commons license of bmc below BMC implementation as BMT MVP
- show link to strategyzer.com
- name changes made compared to original BMC (added fields)

more RtBs/Background in:

https://teams.microsoft.com/l/message/19:e0198cd4c3b24c1c9ee626ef8c943289@thread.skype/1622449696868?tenantId=31544429-24c4-4acd-b62d-7bbb40f43132&groupId=6b17f5fa-c800-49eb-bbc2-9090713f6828&parentMessageId=1622449696868&teamName=equihub%20core&channelName=Valuation%20und%20Deal%20Terms&createdTime=1622449696868

**Comment by rebekkategtmeier** [comment]
decided to redisgn and not use license
