### ISSUE TITLE
[BMT] Integrate Multiple Findings 

### ISSUE THREAD

**Issue by rebekkategtmeier** [andriisemenov/equihub-brain-issue-tracking#89]
Me as a host, 
would like to know which findings a team derivates from the validation of the hypotheses so that I can comment on the progress or support the team if needed. 
Me as a team, 
would like to easily stick to the lean startup process and decide on the right next steps after validating a hypothesis. Therefore I would like to derive my findings and decide on the next steps. 

Acceptance Criteria and Outcomes: 

- [x] user knows which hypothesis they are talking about 
- [x] general comment field is changed into findings 
- [x] user can add multiple findings 
- [x] user can edit and delete a finding 
- [x] host can comment on the findings 
- [x] everyone knows who added the finding

**Comment by rebekkategtmeier** [comment]
![image](https://user-images.githubusercontent.com/76179547/123219244-fa23d000-d4cc-11eb-9c95-271b8f1b320c.png)

![image](https://user-images.githubusercontent.com/76179547/123219174-e37d7900-d4cc-11eb-8b72-391072229eb8.png)

**Comment by andriisemenov** [comment]
Replace "Enter your findings and ..." with the headline
Put "Enter your findings and ..." instead of 
Keep the field non changeable for now.

**Comment by andriisemenov** [comment]
Creating hypothesis

mutation{
  createHypothesisComment(hypothesisComment: {comment:"Hello", hypothesis:"0a4fb349-8ea6-4dc0-9b80-984c4c6c40b6"}){
    id
    comment
  }
}

**Comment by andriisemenov** [comment]
Getting hypothesis + comments + the user that posted the comment. If user is undefined, host is defined and vice versa (can be only user or host, not both at the same time).

query{
  getHypothesisWithComments(hypothesis: "0a4fb349-8ea6-4dc0-9b80-984c4c6c40b6"){
    id
    comments{
      id
      comment
      user{
        firstname
        lastname
      }
      host{
        firstname
        lastname
      }
    }
  }
}

**Comment by andriisemenov** [comment]
Removing hypothesis comment:


mutation{
  removeHypothesisComment(id:"759efebf-d3fd-4986-b777-5d727f575937")
}

**Comment by andriisemenov** [comment]
add editing of the comments

**Comment by kochjh** [comment]
- [ ] In Progress Button Background
- [ ] menu as 3 dots
- [ ] Timestamps
- [ ] Author + date, comment below
- [ ] hide oldest comments
- [ ] scrollbar just for findings

**Comment by andriisemenov** [comment]
Editing hypothesis:

mutation{
  editHypothesisComment(hypothesisComment:{
    id:"ad615e78-9804-42ab-ab1e-aa01164f58ec",
    hypothesis:"ee08cd46-3820-4738-bda5-adb7a2c148b2",
    comment: "HelloChanged"
  })
  {
    id
  }
}
